[package]
name = "test-bevy"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.8.1"
rand = "0.8.5"
ron = "0.8.0"
serde = "1.0.145"
